### PR TITLE
Adding Net and Entrypoint switches to docker call

### PR DESCRIPTION
**Pull request by lovato**
potentially solves… #42 and #43

### CODE REVIEW

**Comment by lovato** [comment]
@mserranom

**Comment by lovato** [comment]
@mserranom hello?

**Comment by lovato** [comment]
@mserranom I offer myself to work on this repository if you think this can help. I don't want to clone your project just to create a bbrun2.

**Comment by lovato** [comment]
@mserranom Can you at least comment something here? It has been almost a year. If you accept it, it would be great. If you decline it, I will probably fork your solution and publish a new one. If you want help with repo maintenance, I will also be glad to.

**Comment by mserranom** [comment]
I'm really sorry @lovato, I'll giving you write permissions to manage contributions. We'd also need to find some way to transfer npm ownership.

**Comment by lovato** [comment]
@mserranom Tks for doing that. I will be more than happy to help. Does NPM require only a single owner? If I can just be added to it, I would be willing to. And if we need to transfer, I would be willing to it too, since I actually like the tool and have use for it.

**Comment by lovato** [comment]
Please, also share your plans for CICD, and everything else, so I can follow your ideas. And I would suggest establishing a communication channel (hangouts, email, whatever) to get stuff in sync.

**Comment by mserranom** [comment]
I enabled github for CI, packages are released using https://github.com/mserranom/bbrun/blob/master/release.sh.

I created a `bbrun` organisation in npmjs and have shared an invite. 

Preferred communication way is github issues. I'm now on top of github activity (using https://octobox.io by the way, highly recommended).

**Pull request merged**
